### ISSUE TITLE
Create product list

### ISSUE THREAD

**Issue by ScriptyChris** [ScriptyChris/Fake-PEV-Shopping#2]
Create product list with the following features:

- [x] presenting products [done in #9]
- [x] categories tree [done in #21]
- [x] filtering (price, name, reviews, release date etc.) [done in #32]
- [x] searching by name [done in #31]
- [x] sorting [done in #57]
- [x] compare [done in #29]
- [x] use lazy loading or pagination to show available products [done in #20]
