### ISSUE TITLE
Maintenance and refactoring of current code base

### ISSUE THREAD

**Issue by ScriptyChris** [ScriptyChris/Fake-PEV-Shopping#22]
A group of actions needed to improve app further development, building and testing:

- [x] configure CI/CD [partially done in #26]
- [x] add unit tests for backend
- [x] refactor backend code to use TypeScript
- [ ] unify HTTP statuses being send from backend into enum and make handling HTTP errors (including frontend) more consistent 
  - [x] backend part done in #45
  - [ ] frontend part
- [x] add E2E tests for frontend [started in #49]
- [x] refactor frontend code to use TypeScript [started in #48]
- [x] use Docker to unify and facilitate way of distributing the app [partially done in #26]
- [ ] add a initial config endpoint to let frontend fetch essential constants (like categories tree and technical specs nesting level or user account types or maximum product rating value) and cache it until config update is done on backend
- [x] add code documentation (with i.e. [JSDoc](https://jsdoc.app/)) and update `README.md` with it's generated markdown output (via i.e. [jsdoc-to-markdown](https://github.com/jsdoc2md/jsdoc-to-markdown/blob/master/docs/API.md#jsdoc-to-markdown)) [#58]
- [x] refactor (frontend) routing to contextually nest/group views [#47]
- [x] refactor `middleware-response-wrapper.ts` module to wrap whole (chained) calls to `res.status(..)`, `res.json(..)`, `res.sendStatus(..)` etc. to have more robust type checking between HTTP status code and response data kind (i.e. `4xx` HTTP codes may only be used with response containing`error` data) [#47]
- [x] remove `models-index.ts` (re-exporting) module and instead import each Schema/Model stuff by individual modules.
  **[update]** this module was renamed and refactored in #54
