### ISSUE TITLE
Create user account authorization features according to specific roles

### ISSUE THREAD

**Issue by ScriptyChris** [ScriptyChris/Fake-PEV-Shopping#23]
Shop may offer it's features for different user roles:

- **client** who can:
  - [x] ~~view products~~ (should _not_ require to have an account)
  - [x] buy products [#27] (**maybe** user should be able to buy a product without being logged in? kind of ad-hoc shopping)
  - [x] add review for bought products [#40]
  - [ ] check purchase info (like delivery status, invoice retrieval, refunding)
  - [x] manage favorites/observed products [#46]
- **seller/retailer** who can:
  - [x] view products
  - [x] add new products
  - [x] edit already added products [#18, #38]
  - [ ] see added products statistics (sales, views)
  - [ ] request shop administrator to add new category
  - [ ] moderate products reviews
- **administrator** who can:
  - [ ] do some maintenance activities
  - [ ] _TBD..._
- _**all**_ of them can:
  - [ ] change their account details (like: password [#46], email, avatar)
  - [x] logout from active sessions
