### ISSUE TITLE
Create user account authentication feature

### ISSUE THREAD

**Issue by ScriptyChris** [ScriptyChris/Fake-PEV-Shopping#5]
- [x] register an account and confirm it [done in #43]
- [x] login to account [done in #15]
- [x] associate user with a specific role (like client or retailer) having permissions [done in #17]
- [x] reset password [done in #44]
